const SHOP_EMAIL = "vhgamerz022008@gmail.com";

const PRODUCTS = [
  {
    id: "rubics-cube",
    name: "Rubic's Cube",
    price: 65,
    category: "creative",
    image: "photos/cube.jpg.jpeg",
    rating: 4.8,
    stock: "In Stock",
    description: "A smooth rotating Rubik's Cube perfect for beginners and speed cube enthusiasts.",
    features: ["Smooth Rotation", "Stickerless Design", "High Quality ABS Plastic", "Lightweight", "Long Lasting"],
    specifications: { Brand: "Rezell", Material: "ABS Plastic", Weight: "90 g", Color: "Multicolor" },
    reviews: [
      { name: "Asha", rating: 5, comment: "Excellent quality and very smooth to rotate." },
      { name: "Rohan", rating: 4, comment: "Great for daily practice and gifting." }
    ]
  },
  {
    id: "tape",
    name: "Tape",
    price: 55,
    category: "essential",
    image: "photos/tape.jpg.jpeg",
    rating: 4.7,
    stock: "In Stock",
    description: "Strong transparent tape suitable for school, office and home use.",
    features: ["Strong Adhesive", "Easy Tear", "Water Resistant", "Clear Finish"],
    specifications: { Length: "25 m", Width: "2 inch", Material: "Plastic" },
    reviews: [{ name: "Meera", rating: 5, comment: "Very strong grip and easy to use." }]
  },
  {
    id: "phone-stand",
    name: "Phone Stand",
    price: 49,
    category: "creative",
    image: "photos/phone stand.jpg.jpeg",
    rating: 4.9,
    stock: "In Stock",
    description: "Foldable mobile stand compatible with all smartphones.",
    features: ["Foldable", "Adjustable Angle", "Compact", "Anti Slip Base"],
    specifications: { Material: "ABS", Weight: "80 g", Compatibility: "All Phones" },
    reviews: [{ name: "Kunal", rating: 5, comment: "Perfect for bedside use and desk work." }]
  },
  {
    id: "earphone-case",
    name: "Earphones Carrying Case",
    price: 59,
    category: "creative",
    image: "photos/HeadphonesCarryingCase.jpg.jpeg",
    rating: 4.8,
    stock: "In Stock",
    description: "Protect your earphones with a premium hard carrying case.",
    features: ["Hard Shell", "Water Resistant", "Compact", "Zipper Closure"],
    specifications: { Material: "EVA", Weight: "65 g" },
    reviews: [{ name: "Naina", rating: 4, comment: "Looks premium and protects my earbuds well." }]
  },
  {
    id: "silicon-holder",
    name: "Silicon Phone Holder",
    price: 55,
    category: "creative",
    image: "photos/silicon phone holder.jpg.jpeg",
    rating: 4.6,
    stock: "In Stock",
    description: "Flexible silicon holder for easy mobile placement anywhere.",
    features: ["Flexible", "Durable", "Washable", "Reusable"],
    specifications: { Material: "Silicone", Color: "Random" },
    reviews: [{ name: "Jiya", rating: 5, comment: "Very handy and easy to place on the desk." }]
  },
  {
    id: "wall-holder",
    name: "Mobile Charging Wall Holder",
    price: 99,
    category: "creative",
    image: "photos/mobile charging wall holder.jpg.jpeg",
    rating: 4.8,
    stock: "In Stock",
    description: "Wall mounted charging holder to safely keep your phone while charging.",
    features: ["Easy Installation", "Strong Plastic", "Compact", "Cable Friendly"],
    specifications: { Material: "Plastic", Weight: "150 g" },
    reviews: [{ name: "Priyesh", rating: 5, comment: "Very practical and clean setup." }]
  },
  {
    id: "glass-bottle",
    name: "Glass Water Bottle 400ml",
    price: 129,
    category: "essential",
    image: "photos/Glass Water Bottle 400ml Leak Proof – BPA-Free for Gym & Travel.jpg.jpeg",
    rating: 4.9,
    stock: "In Stock",
    description: "Premium leak proof glass bottle ideal for gym, office and travel.",
    features: ["Leak Proof", "BPA Free", "Portable", "Reusable"],
    specifications: { Capacity: "400ml", Material: "Glass", Lid: "Leak Proof" },
    reviews: [{ name: "Sneha", rating: 5, comment: "Great bottle for travel and gym." }]
  },
  {
    id: "mobile-holder-pack",
    name: "Wall Mounted Mobile Holder (4 Pack)",
    price: 75,
    category: "creative",
    image: "photos/Wall Mounted Mobile Holder – 4 Pack Plastic Organizer.jpg.jpeg",
    rating: 4.7,
    stock: "In Stock",
    description: "Wall mounted organizer for storing phones, remotes and accessories.",
    features: ["Pack of 4", "Easy Install", "Strong Plastic", "Multi Purpose"],
    specifications: { Material: "Plastic", Pieces: "4" },
    reviews: [{ name: "Krishna", rating: 4, comment: "A useful organizer for the bedroom." }]
  },
  {
    id: "4-in-1-fast-charging-cable",
    name: "4-in-1 65W Fast Charging Cable",
    price: 99,
    category: "essential",
    image: "photos/65W 4-in-1 Fast Charging Cable – Durable Multi-Port Charger.jpg.jpeg",
    rating: 4.8,
    stock: "In Stock",
    description: "Premium 4-in-1 fast charging cable with USB, USB-C, Lightning, and Micro USB connectors. Supports up to 65W PD fast charging and is built with a durable braided cable for everyday use.",
    features: ["4-in-1 Multi Connector", "65W PD Fast Charging", "Durable Braided Cable", "USB, USB-C, Lightning & Micro USB", "Strong Metal Connectors", "Tangle-Free Design", "High-Speed Data Transfer", "Compatible with Android & iPhone"],
    specifications: { Brand: "Rezell", Power: "65W Max", CableType: "4-in-1 Fast Charging Cable", Connectors: "USB, USB-C, Lightning, Micro USB", Material: "Braided Nylon + Metal Alloy", Length: "1.2 m", Color: "Black & Yellow", Compatibility: "Android, iPhone, Tablets, Power Banks, Laptops" },
    reviews: [{ name: "Divya", rating: 5, comment: "Excellent for all my devices in one cable." }]
  },
  {
    id: "garlic-crusher",
    name: "Garlic Crusher – Manual Mincer & Chopper for Kitchen",
    price: 119,
    category: "essential",
    image: "photos/garlic-crusher.jpg",
    rating: 4.2,
    stock: "In Stock",
    description: "A compact manual garlic crusher and mincer designed to make chopping, mincing and crushing garlic, ginger and onions quick and effortless in the kitchen.",
    features: ["Manual Operation", "Compact Design", "Easy to Clean", "Stainless Steel Blades", "Detachable Container", "Ideal for Garlic, Ginger & Onion"],
    specifications: { Brand: "Quickslice", Material: "Plastic + Stainless Steel", Color: "Green", Type: "Manual Garlic Crusher & Mincer" },
    reviews: [{ name: "Neha", rating: 5, comment: "Very handy and easy to use for daily cooking." }]
  },
  {
    id: "vegetable-cutter",
    name: "Vegetable Cutter & Peeler for Kitchen",
    price: 79,
    category: "essential",
    image: "photos/vegetable-cutter.png",
    rating: 4.3,
    stock: "In Stock",
    description: "A practical 2-in-1 kitchen tool designed for quick peeling and cutting of vegetables and fruits with less effort.",
    features: ["2-in-1 Design", "Easy Peeling", "Quick Cutting", "Compact & Lightweight", "Ergonomic Grip", "Great for Kitchen Use"],
    specifications: { Brand: "ChefAura", Material: "Stainless Steel + Plastic", Color: "Blue", Type: "Vegetable Cutter & Peeler" },
    reviews: [{ name: "Sanjana", rating: 5, comment: "Very useful for daily cooking and peeling." }]
  },
  {
    id: "manual-food-chopper",
    name: "Manual Food Chopper 650ml for Kitchen",
    price: 129,
    category: "essential",
    image: "photos/manual-food-chopper.png",
    rating: 4.4,
    stock: "In Stock",
    description: "A compact manual food chopper with a 650ml capacity that helps you quickly chop onions, tomatoes, herbs, and vegetables for everyday cooking.",
    features: ["650ml Capacity", "Manual Operation", "Easy to Use", "Safe Handle", "Leak-Resistant Container", "Perfect for Daily Prep"],
    specifications: { Brand: "Quickslice", Material: "Plastic + Stainless Steel", Capacity: "650ml", Color: "Green", Type: "Manual Food Chopper" },
    reviews: [{ name: "Arjun", rating: 5, comment: "Great for chopping vegetables quickly and neatly." }]
  },
  {
    id: "divider-holder",
    name: "Multipurpose Divider Holder with 5 Compartments for Organized Spaces",
    price: 139,
    category: "home",
    image: "photos/divider holder.webp",
    rating: 4.5,
    stock: "In Stock",
    description: "Organize your desk or drawer with this multipurpose divider holder featuring five compartments for pens, scissors, stationery, and small items.",
    features: ["5 Compartments", "Multipurpose Organizer", "Compact Design", "Durable Material", "Easy to Clean"],
    specifications: { Material: "Plastic", Color: "Gray", Size: "Compact", Type: "Divider Holder" },
    reviews: [{ name: "Pooja", rating: 5, comment: "Perfect for organizing my desk supplies." }]
  },
  {
    id: "wooden-chopping-board",
    name: "Wooden Chopping Board 30x20",
    price: 99,
    category: "home",
    image: "photos/chopping-board-1.jpg",
    rating: 4.3,
    stock: "In Stock",
    description: "A durable 30x20 cm wooden chopping board designed for effortless vegetable cutting, chopping, and prep work in the kitchen.",
    features: ["Durable Wood", "30x20 cm Size", "Water Resistant Finish", "Reversible Use", "Easy to Clean"],
    specifications: { Brand: "Cisora", Material: "Wood", Color: "Natural Brown", Size: "30x20 cm", Type: "Chopping Board" },
    reviews: [{ name: "Deepa", rating: 5, comment: "Sturdy and perfect for everyday vegetables." }]
  },
  {
    id: "heavy-cutter-knife",
    name: "Heavy Cutter Knife 1pc No11",
    price: 79,
    category: "essential",
    image: "photos/cutter-knife-1.jpg",
    rating: 4.4,
    stock: "In Stock",
    description: "A heavy-duty utility cutter knife with a precision blade for cutting cardboard, packaging, and crafts with ease.",
    features: ["Sturdy Blade", "Comfort Grip", "Easy Blade Change", "Compact Size", "Precision Cutting"],
    specifications: { Brand: "Indo Glow", Material: "Steel", Color: "Silver", Size: "1 pc", Type: "Utility Cutter Knife" },
    reviews: [{ name: "Ravi", rating: 4, comment: "Good quality knife for cutting through thicker material." }]
  },
  {
    id: "hot-melt-glue-gun",
    name: "20W Hot Melt Glue Gun",
    price: 109,
    category: "creative",
    image: "https://deodap.in/cdn/shop/files/Glue-gun-01.jpg?v=1761367712",
    rating: 4.7,
    stock: "In Stock",
    description: "Fast-heating 20W hot melt glue gun designed for quick, precise adhesive application in crafts, repairs, DIY projects, and household tasks.",
    features: ["Fast Heating", "Anti-Drip Nozzle", "Ergonomic Grip", "Fold-Out Stand", "Ideal for Crafts & Repairs"],
    specifications: { Brand: "DeoDap", Power: "20W", Type: "Hot Melt Glue Gun", Material: "Plastic + Metal", Color: "Black", Use: "Crafts, Repairs, DIY" },
    reviews: [
      { name: "Nidhi", rating: 5, comment: "Heats quickly and works great for small craft projects." },
      { name: "Aman", rating: 4, comment: "Very handy for quick repairs around the house." }
    ]
  },
  {
    id: "bookmark",
    name: "Custom Name Bookmark",
    price: 59,
    category: "creative",
    image: "photos/bookmark.svg?v=2",
    rating: 4.9,
    stock: "Made to Order",
    description: "Personalized bookmark with your custom name.",
    features: ["Personalized", "Premium Card", "Laminated", "Gift Ready"],
    specifications: { Material: "Card Sheet" },
    reviews: [{ name: "Arun", rating: 5, comment: "A lovely gift and looks amazing." }]
  },
  {
    id: "coasters",
    name: "Fabric Coasters (Set of 4)",
    price: 199,
    category: "creative",
    image: "photos/coaster.svg?v=2",
    rating: 4.9,
    stock: "Made to Order",
    description: "Hand stitched fabric coasters designed to protect your table in style.",
    features: ["Handmade", "Washable", "Premium Fabric", "Set of 4"],
    specifications: { Material: "Cotton", Pieces: "4" },
    reviews: [{ name: "Kavya", rating: 5, comment: "Elegant and very well crafted." }]
  }
];